server: 
  port: 8088
  application: 
    name: open-feign-client
    
feign:
  client:
    config:
      weather:
        errorDecoder: com.example.ofc.feign.MyErrorDecoder
        retryer: com.example.ofc.feign.MyRetryer
